apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-luds
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-luds@sha256:a6758955063a2a314ec2fa335cd251b3a9acd7b6f2a302ab692a58b73542b836
        name: my-nodejs
        resources: {}
status: {}
